### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by Artucuno** [oskikiboy/RandomStuff#1]
```
  File "main.py", line 34
    print(f"Plugin {num}: {x}")
                             ^
SyntaxError: invalid syntax
```
When i run the script it shows this even tho i have the requirements

btw good job :D

**Comment by Artucuno** [comment]
i found the errors btw
can i have perms to edit to fix?

**Comment by oskikiboy** [comment]
No, this is your error unfortunantly, you do not have python >= 3.6 anything else will error

**Comment by oskikiboy** [comment]
Declaring this issue as closed
